### ISSUE TITLE
NumberFormatException when loading data file

### ISSUE THREAD

**Issue by objectDisorientedProgrammer** [objectDisorientedProgrammer/Quasar2#74]
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "Test data"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at quasar.EntryController.loadFile(EntryController.java:122)
        at quasar.EntryController.<init>(EntryController.java:60)
        at quasar.Quasar.main(Quasar.java:64)
```
from **Test data** in 
```
Test data
0¶test all¶¶    -  -  ¶
1¶test cont¶contact¶2020-08-22¶¶¶¶¶
2¶test doc¶document¶2020-08-22¶¶C:\Users\Doug\Documents¶¶¶
3¶test pic¶picture¶2020-08-22¶¶¶¶0¶0
4¶test web¶website¶2020-08-22¶¶eclipse.org
0¶another new¶after change from |¶    -  -  ¶
```

### Proposed solution
Skip lines from the beginning of the file until the first character isNumeric().

**Comment by objectDisorientedProgrammer** [comment]
Also check that the number is within the range of types and that the following character is the separator.
